/*
 * File: app/store/MaterialTypes.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.store.MaterialGroupStore', {
    extend: 'Ext.data.Store',
    alias: 'store.MaterialGroupStore',

    requires: [
        'Feed.model.MaterialGroupModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'Feed.model.MaterialGroupModel',
        storeId: 'MaterialGroupStoreId',
        proxy: {
            type: 'ajax',
            url:CfgConst.materialGroupQueryUrl,
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        }
    }
});
