/*
 * File: app/store/Items.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.store.NetOrderStore', {
    extend: 'Ext.data.Store',
    alias: 'store.NetOrderStore',

    requires: [
        'Feed.model.NetOrderModel',
        'Feed.model.CustomerModel',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'Feed.model.NetOrderModel',
        storeId: 'NetOrderStoreId',
        proxy: {
            type: 'ajax',
            url: "http://"+CfgConst.host+":"+CfgConst.port+"/d/q/netOrder.json",
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        }
    },

    loadList: function(itemUrl, numItems) {
        this.load({
            params:{
            //    q: itemUrl,
                num: numItems || 20
            }
        });
    }

});