/*
 * File: app/view/ItemList.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.view.AddFormView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.AddFormView',

    requires: [
    ],

    config: {
        id:'AddFormViewId',//sth wrong。see source
        items: [
            {
                xtype: 'fieldset',
                title: '选择商品',
                margin:'.5em .5em .5em',
                items: [
                    {
                        xtype: 'selectfield',
                        label: '类目',
                        labelWidth: '35%',
                        required: true,
                        placeHolder: '商品分组',
                        readOnly: false,
                        store:'MaterialGroupStoreId',
                        displayField:'name',
                        valueField:'id',
                        id:"materialTypeSelectId",
                        name:'materialGroup'
                    },
                    {
                        xtype: 'selectfield',
                        label: '商品',
                        labelWidth: '35%',
                        required: true,
                        displayField:'name',
                        valueField:'id',
                        store:'MaterialStoreId',
                        id:'materialSelectId',
                        placeHolder:'先选择类目',
                        name:'material'
                    },
                    {
                        xtype: 'selectfield',
                        label: '单位',
                        labelWidth: '35%',
                        required: true,
                        placeHolder: '先选择商品',
                        displayField:'name',
                        valueField:'id',
                        store:'MeasureUnitStoreId',
                        id:'measureUnitSelectId',
                        name:'measureUnit'
                    },
                    {
                        xtype: 'numberfield',
                        label: '数量',
                        labelWidth: '35%',
                        required: true,
                        id:'numFieldId',
                        name:'qty',
                        placeHolder: '输入数字'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: '订单金额',
                margin:'.5em .5em .5em',
                items: [
                    {
                        xtype: 'numberfield',
                        label: '单价',
                        labelWidth: '35%',
                        readOnly: true,
                        id:'priceFieldId',
                        name:'price',
                        placeHolder: '不能输入哦'
                    },
                    {
                        xtype: 'numberfield',
                        label: '金额',
                        labelWidth: '35%',
                        readOnly: true,
                        id:'amountFieldId',
                        name:'amount',
                        placeHolder: '不能输入哦'
                    },{
                        xtype:'hiddenfield',
                        name:'test',
                        value:'中文'
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                margin:'.5em .5em .5em',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        height: 40,
                        ui: 'decline',
                        width: '35%',
                    //    icon: 'true',
                    //    iconCls: 'delete',
                        text: '清空',
                        id:'clearBtnId'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        height: 40,
                        ui: 'confirm',
                        width: '55%',
                    //    icon: 'true',
                    //    iconCls: 'add',
                        text: '加入购物车',
                        id:'addCarBtnId'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'spacer'
                    }
                ]
            }
        ]
    }
});
