/*
 * File: app/view/ItemList.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.view.NetOrderList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.NetOrderList',

    requires: [
        'Ext.XTemplate',
        'Feed.store.NetOrderStore'
    ],

    config: {
        id: 'NetOrderListId',
        store: 'NetOrderStoreId',
        itemTpl: [
            '<table style="font-size: small;" width="100%">',
            '<tr style="background-color:yellowgreen;" width="100%"><td colspan="2">{number}</td></tr>',
            '<tr>' +
                '<td width="85%">',
                    '<table>',
                        '<tr><td align="right" width="45%">业务日期：</td><td width="55%">{[values.bizDate.toLocaleTimeString()]}</td></tr>',
                        '<tr><td align="right">金额数量：</td><td>￥{amount} &nbsp; ({qty}) </td></tr>',
                        '<tr><td align="right">要货日期：</td><td>{[values.askArriveDate.toLocaleDateString()]}</td></tr>',
                        '<tr><td align="right">单据状态：</td><td>{billStatusDesc}<tpl if="isFightBack">（打回）</tpl></td></tr>',
                    '</table>',
                '</td>' +
                '<td width="15%" align="center" valign="center"><a href="javascript:void(0);" onclick="Ext.getCmp(\'NetOrderListId\').abc({id});return false;"> > </a></td>',
            '</tr></table>',
        ]
    },

    abc:function(ee){
        alert(ee);
    }
});