/*
 * File: app/view/ItemList.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.view.NetOrderList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.NetOrderList',

    requires: [
        'Ext.XTemplate',
        'Feed.store.NetOrderStore'
    ],

    config: {
        id: 'NetOrderListId',
        store: 'NetOrderStoreId',
        itemTpl: [
            '<div>',
            '编号：{number}   业务日期：{bizDate} <br>',
            '订购数量：{qty}  订购金额:{amount}<br>',
            '要求到货日期：{askArriveDate}  订单状态:{billStatusDesc} 是否打回:{isFightBack}<br>',
            '经销商：{customerVO.name}   销售组织：{saleOrgUnitVO.name} <br>',
            '</div>',
            '<div>',
            '<input type=\'button\' value=\'del\'/>',
            '    </div>',
            ''
        ]
    }
});