/*
 * File: app/view/ItemList.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.view.NetOrderDetail', {
    extend: 'Ext.form.Panel',
    alias: 'widget.NetOrderDetail',

    requires: [
    ],

    config: {
        itemId: 'formCancelBtn',
        padding: '10px',
        items: [
            {
                xtype: 'textfield',
                margin: '5px 0 0 0',
                label: '订单编号',
                labelAlign: 'left',
                name: 'number',
                labelWidth: '40%',
                id:'orderNumId',
                readOnly: true
            },
            {
                xtype: 'datepickerfield',
                margin: '5px 0 0 0',
                label: '业务日期',
                labelAlign: 'left',
                name: 'bizDate',
                labelWidth: '40%',
                id:'bizDateTxtId',
                readOnly: true,
                dateFormat:'Y-m-d'
            },
            {
                xtype: 'textfield',
                margin: '5px 0 0 0',
                label: '金额',
                labelAlign: 'left',
                name: 'amount',
                labelWidth: '40%',
                id:'amountTxtId',
                readOnly: true
            },
            {
                xtype: 'textfield',
                margin: '5px 0 0 0',
                label: '数量',
                labelAlign: 'left',
                name: 'qty',
                labelWidth: '40%',
                id:'numTxtId',
                readOnly: true
            },
            {
                xtype: 'datepickerfield',
                margin: '5px 0 0 0',
                label: '要货日期',
                labelAlign: 'left',
                name: 'askArriveDate',
                labelWidth: '40%',
                id:'ackDatePickId',
                readOnly: true,
                dateFormat:'Y-m-d'
            },
            {
                xtype: 'textfield',
                margin: '5px 0 0 0',
                label: '单据状态',
                labelAlign: 'left',
                name: 'billStatusDesc',
                labelWidth: '40%',
                id:'billStatusId',
                readOnly: true
            },
            {
                xtype: 'list',
                fullscreen: true,
                itemTpl: 'abc'
            }

        ]
    },

    setRecord: function(record) {
        this.callParent(arguments);
        if (record) {

        }
    }
});