/*
 * File: app/view/ItemList.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.view.ShoppingCarList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.ShoppingCarList',

    requires: [
        'Ext.XTemplate',
        'Feed.store.ShoppingCarStore'
    ],

    config: {
        id: 'ShoppingCarListId',
        store: 'ShoppingCarStoreId',
        itemTpl: [
            '<table style="font-size: small;" width="100%">',
            '<tr style="background-color:yellowgreen;" width="100%">' +
                '<td  width="80%"><b>{materialName}</b></td>' +
                '<td width="20%" align="center"><a href="javascript:void(0)" onclick="Ext.getCmp(\'ShoppingCarListId\').fireEvent(\'delEvent\',{id});">删除</a></td>' +
            '</tr></table><table>' +
            '<tr><td align="right" width="45%">选购日期：</td><td width="55%">{[values.shopDate.toLocaleDateString()]}</td></tr>',
            '<tr><td align="right">订单总额：</td><td>￥{amount}</td></tr>',
            '<tr><td align="right">选购数量：</td><td>{qty} {measureName}</td></tr>',
            '<tr><td align="right">商品价格：</td><td>{price}</td></tr>',
            '<tr><td align="right">销售渠道：</td><td>{channel}</td></tr>',
            '</table>',
        ],
        loadingText:'加载中...'
    }
});