/*
 * File: app/view/TabPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.view.TabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabpanel',

    requires: [
        'Feed.view.ItemList',
        'Ext.navigation.View',
        'Ext.dataview.List',
        'Ext.navigation.Bar',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Number',
        'Ext.Spacer',
        'Ext.tab.Bar'
    ],

    config: {
        id:'TabPanelId',

        items: [
            {
                xtype: 'container',
                title: '购物车',
                iconCls: 'home',
                id: 'itemsTab',
                layout: 'fit',
                items: [
                    {
                        xtype: 'navigationview',
                        id: 'itemsNav',
                        useTitleForBackButtonText: true,
                        items: [
                            {
                                xtype: 'ItemList',
                                id: 'CarItemListId',
                                title: '我的购物车'
                            }
                        ],
                        navigationBar: {
                            items: [
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    id: 'refreshBtn',
                                    ui: 'action',
                                    iconCls: 'refresh',
                                    text: '',
                                    handler:function(){
                                        Ext.getStore("ItemsId").loadCarItems();
                                    }
                                }
                            ]
                        }
                    }
                ]
            },
            {
                xtype: 'container',
                title: '下单',
                iconCls: 'add',
                id: 'addTab',
                layout: 'fit',
                items: [
                    {
                        xtype: 'AddFormView',
                         id: 'AddFormViewId'
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});