/*
 * File: app/view/TabPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.view.TabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabpanel',

    requires: [
        'Feed.view.ItemList',
        'Ext.navigation.View',
        'Ext.dataview.List',
        'Ext.navigation.Bar',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Number',
        'Ext.Spacer',
        'Ext.tab.Bar'
    ],

    config: {
        items: [
            {
                xtype: 'container',
                title: '购物车',
                iconCls: 'home',
                id: 'itemsTab',
                layout: 'fit',
                items: [
                    {
                        xtype: 'navigationview',
                        id: 'itemsNav',
                        useTitleForBackButtonText: true,
                        items: [
                            {
                                xtype: 'ItemList',
                                id: 'CarItemListId',
                                title: '我的购物车'
                            }
                        ],
                        navigationBar: {
                            items: [
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    id: 'refreshBtn',
                                    ui: 'action',
                                    iconCls: 'refresh',
                                    text: '',
                                    handler:function(){
                                        Ext.getStore("ItemsId").loadCarItems();
                                    }
                                }
                            ]
                        }
                    }
                ]
            },
            {
                xtype: 'container',
                title: '下单',
                iconCls: 'add',
                id: 'addTab',
                layout: 'fit',
                items: [
                    {
                        xtype: 'formpanel',
                        items: [
                            {
                                xtype: 'fieldset',
                                title: '选择商品',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        label: '物料分类',
                                        labelWidth: '35%',
                                        required: true,
                                        placeHolder: '选择物料分类',
                                        readOnly: false
                                    },
                                    {
                                        xtype: 'selectfield',
                                        label: '商品',
                                        labelWidth: '35%',
                                        required: true,
                                        placeHolder: '需要下单的商品'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        label: '计量单位',
                                        labelWidth: '35%',
                                        required: true,
                                        placeHolder: '可切换'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        label: '数量',
                                        labelWidth: '35%',
                                        required: true
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                title: '订单金额',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        label: '单价',
                                        labelWidth: '35%',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'numberfield',
                                        label: '金额',
                                        labelWidth: '35%',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'button',
                                        height: 40,
                                        ui: 'decline',
                                        width: '35%',
                                        icon: 'true',
                                        iconCls: 'delete',
                                        text: '清空'
                                    },
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'button',
                                        height: 40,
                                        ui: 'confirm',
                                        width: '50%',
                                        icon: 'true',
                                        iconCls: 'add',
                                        text: '添加购物车'
                                    },
                                    {
                                        xtype: 'spacer'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});