/*
 * File: app/model/Item.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.model.NetOrderModel', {
    extend: 'Ext.data.Model',
    alias: 'model.NetOrderModel',

    requires: [
        'Ext.data.Field',
        'Feed.model.CustomerModel'
    ],

    config: {
        fields: [
            {
                name: 'number'
            },
            {
                name: 'id'
            },
            {
                name: 'bizDate',
                type: 'date',
                //convert:this.long2Date
                dateFormat:'time'
            },
            {
                name: 'qty'
            },
            {
                name: 'amount'
            },
            {
                name: 'askArriveDate',
                type: 'date',
                dateFormat:'time'
            },
            {
                name: 'billStatusDesc'
            },
            {
                name: 'billStatus'
            },
            {
                mapping:'fightBack',
                name: 'isFightBack'
            },
            {
                name:'customerVO'
            },{
                name:'saleOrgUnitVO'
            }
        ],
        hasOne:{model:"SaleOrgUnitModel",name:'saleOrgUnitVO'},
        hasOne:{model:"CustomerModel",name:'customerVO'}
    },

    long2Date:function(v,record){
        return new Date(v);
    }
});

function adfa(v,record){
    return new Date(v);
}