/*
 * File: app/model/Item.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.model.ShoppingCarModel', {
    extend: 'Ext.data.Model',
    alias: 'model.ShoppingCarModel',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'qty'
            },
            {
                name: 'id'
            },
            {
                name: 'price'
            },
            {
                name: 'amount'
            },
            {
                //mapping: 'publishedDate',
                //name: 'date',
                name: 'channel'
            },
            {
                //mapping: 'publishedDate',
                type: 'date',
                name: 'shopDate',
                dateFormat:'time'
            },
            {
                name: 'saleOrgUnitId'
            },
            {
                mapping:"measureUnitVO.id",
                name:"measureUnitId"
            },{
                mapping:"measureUnitVO.name",
                name:"measureUnitName"
            },
            {
                    mapping:"materialVO.id",
                name:"materialId"
            },{
                mapping:"materialVO.name",
                name:"materialName"
            }
        ]
    }
});