/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});

var CfgConst=new Object();
CfgConst.host='192.168.1.109';
CfgConst.port=8080;

CfgConst.materialGroupQueryUrl = "/mobile/mborder/q/materialGroup.json?mock=true";
CfgConst.measureUnitQueryUrl = "/mobile/mborder/q/measureUnit.json?mock=true";
CfgConst.materialQueryUrl = "/mobile/mborder/q/material.json?mock=true";
CfgConst.shoppingCardQueryUrl = "/mobile/mborder/q/shoppingCarList.json?mock=true"
CfgConst.netOrderQueryUrl = "/mobile/mborder/q/netOrder.json?mock=true"

CfgConst.addCarUrl = "/mobile/mborder/o/addCar.json?mock=true";
CfgConst.delCarUrl = "/mobile/mborder/o/delCar.json?mock=true";
CfgConst.calPriceUrl = "/mobile/mborder/o/calPrice.json?mock=true";

Ext.application({

    requires: [
        'Ext.MessageBox'
    ],
    models: [
        'ShoppingCarModel',
        'NetOrderModel',
        'MaterialGroupModel',
        'MaterialModel',
        'MeasureUnitModel',
        'CustomerModel',
        'SaleOrgUnitModel',
        "FormValidatorModel"
    ],
    stores: [
        'ShoppingCarStore',
        'MaterialGroupStore',
        'MaterialStore',
        'MeasureUnitStore',
        'AddFormStore',
        'NetOrderStore',
        'MaterialPriceStore'
    ],
    views: [
        'TabPanel',
        'ShoppingCarList',
        'NetOrderList',
        'AddFormView',
        'NetOrderDetail'
    ],
    controllers: [
        'ShoppingCarController',
        'AddFormController',
        'NetOrderController'
    ],
    name: 'Feed',

    launch: function() {
        Ext.create('Feed.view.TabPanel', {fullscreen: true});
    }
});
