/*
 * File: app/view/ItemList.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Feed.view.ItemList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.itemlist',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        id: 'postsList',
        store: 'Items',
        itemTpl: [
            '<div>',
            '标题：{title}  <br>',
            '作者：{author}<br>',
            '时间：{date}<br>',
            '</div>',
            '<div>',
            '<input type=\'button\' value=\'del\'/>',
            '    </div>',
            ''
        ]
    }

});